-- ==============================================================================
-- EDGEWFORCE ENTERPRISE — PRODUCTION MASTER DATABASE SCHEMA & SEED SCRIPT
-- For Supabase PostgreSQL (Run directly in Supabase SQL Editor)
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. COMPANIES (Multi-Tenancy Root)
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    business_type TEXT DEFAULT 'Distribution',
    industry TEXT DEFAULT 'FMCG',
    registration_number TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    country TEXT DEFAULT 'Nigeria',
    state TEXT DEFAULT 'Lagos',
    city TEXT DEFAULT 'Lagos',
    logo_url TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'onboarding')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT companies_uuid_unique UNIQUE(uuid),
    CONSTRAINT companies_email_unique UNIQUE(email)
);

-- 2. COMPANY SETTINGS (Receipt Customization & Telemetry Config)
CREATE TABLE IF NOT EXISTS public.company_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT UNIQUE NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    working_days TEXT[] DEFAULT ARRAY['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    working_hours_start TEXT DEFAULT '08:00',
    working_hours_end TEXT DEFAULT '17:00',
    work_start_time TIME DEFAULT '08:00:00',
    work_end_time TIME DEFAULT '17:00:00',
    timezone TEXT DEFAULT 'Africa/Lagos',
    geofence_radius INTEGER DEFAULT 150,
    geofence_radius_meters INTEGER DEFAULT 150,
    currency TEXT DEFAULT 'NGN',
    receipt_company_name TEXT DEFAULT 'EXPERIENTIAL EDGE',
    receipt_tagline TEXT DEFAULT 'Integrated Marketing & Commercial Distribution Solutions',
    receipt_title TEXT DEFAULT 'EEDGED2U SALES RECEIPT',
    receipt_address TEXT DEFAULT 'No 15, Atiba Osborne Mende, Maryland, Lagos, Nigeria',
    receipt_phone TEXT DEFAULT '+2348006393435',
    receipt_footer_note TEXT DEFAULT 'Goods received in good condition are not returnable after 48 hours. Thank you for your business!',
    attendance_rules JSONB DEFAULT '{"require_gps": true, "require_selfie": false, "auto_checkout": true}'::jsonb,
    visit_rules JSONB DEFAULT '{"min_duration_minutes": 15, "require_photo": true, "require_signature": true}'::jsonb,
    sales_targets JSONB DEFAULT '{"monthly_target_ngn": 10000000, "commission_percent": 5}'::jsonb,
    active_modules JSONB DEFAULT '{"workforce": true, "attendance": true, "field": true, "sales": true, "crm": true, "payments": true, "inventory": true, "delivery": true, "reports": true, "tracking": true}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. DEPARTMENTS & RANKS
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ranks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    level INTEGER NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT
);

-- 4. USERS & PASSWORDS
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT UNIQUE,
    raw_phone TEXT,
    password_hash TEXT NOT NULL,
    role_code TEXT NOT NULL DEFAULT 'STAFF_MEMBER',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    requires_password_change BOOLEAN DEFAULT TRUE,
    password_changed_at TIMESTAMPTZ,
    first_login_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    onboarding_status TEXT DEFAULT 'Account Created',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. EMPLOYEES
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    employee_code TEXT UNIQUE NOT NULL,
    staff_id TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    full_name TEXT,
    personal_email TEXT,
    work_email TEXT,
    phone TEXT,
    date_of_birth TEXT,
    marital_status TEXT,
    nationality TEXT DEFAULT 'Nigerian',
    address TEXT,
    home_address TEXT,
    city_lga TEXT,
    state_of_origin TEXT,
    state_of_residence TEXT,
    landmark TEXT,
    department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL,
    department TEXT,
    department_raw TEXT,
    position TEXT,
    date_of_joining TEXT,
    work_location TEXT,
    supervisor_name TEXT,
    territory TEXT,
    supervisor_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    rank_code TEXT,
    base_salary NUMERIC(15,2) DEFAULT 0,
    housing_allowance NUMERIC(15,2) DEFAULT 0,
    transport_allowance NUMERIC(15,2) DEFAULT 0,
    other_allowance NUMERIC(15,2) DEFAULT 0,
    emergency_contact_name TEXT,
    emergency_contact_relationship TEXT,
    emergency_contact_phone TEXT,
    blood_group TEXT,
    bank_name TEXT,
    account_number TEXT,
    hobbies_interests TEXT,
    flagged_for_review BOOLEAN DEFAULT FALSE,
    review_reason TEXT,
    onboarding_status TEXT DEFAULT 'Account Created',
    performance_score NUMERIC(5,2) DEFAULT 90.0,
    hire_date DATE DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'terminated', 'on_leave')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. WORK LOCATIONS & GEOFENCING
CREATE TABLE IF NOT EXISTS public.work_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    location_type TEXT DEFAULT 'Office',
    address TEXT,
    state TEXT DEFAULT 'Lagos',
    lga TEXT,
    city TEXT DEFAULT 'Lagos',
    region TEXT DEFAULT 'South-West',
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    geofence_radius INTEGER DEFAULT 150,
    geofence_radius_meters INTEGER DEFAULT 150,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.employee_location_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES public.work_locations(id) ON DELETE CASCADE,
    assignment_type TEXT DEFAULT 'primary' CHECK (assignment_type IN ('primary', 'secondary', 'temporary')),
    is_primary BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE,
    reason TEXT,
    assigned_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. CUSTOMERS & OUTLETS
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    business_name TEXT,
    customer_type TEXT DEFAULT 'Retail',
    tier TEXT DEFAULT 'Tier 1',
    territory TEXT DEFAULT 'Lagos Mainland',
    address TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    geofence_radius INTEGER DEFAULT 150,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    credit_limit NUMERIC(15,2) DEFAULT 1000000.00,
    balance NUMERIC(15,2) DEFAULT 0.00,
    assigned_agent_id BIGINT,
    assigned_supervisor_id BIGINT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    store_type TEXT DEFAULT 'Supermarket',
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    territory TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    geofence_radius INTEGER DEFAULT 150,
    supervisor_id BIGINT,
    assigned_field_agents BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    assigned_sales_agents BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.store_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    store_name TEXT NOT NULL,
    address TEXT NOT NULL,
    store_type TEXT DEFAULT 'Supermarket',
    contact_person TEXT,
    phone TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    accuracy NUMERIC,
    requested_by BIGINT,
    supervisor_id BIGINT,
    status TEXT DEFAULT 'pending',
    territory TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. PRODUCTS & COMMERCIAL INVENTORY
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    sku TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    category TEXT,
    brand TEXT,
    unit TEXT DEFAULT 'carton',
    cost_price NUMERIC(15,2) DEFAULT 0,
    price NUMERIC(15,2) DEFAULT 0,
    selling_price NUMERIC(15,2) DEFAULT 0,
    stock_quantity INTEGER DEFAULT 100,
    reorder_level INTEGER DEFAULT 20,
    min_stock_alert INTEGER DEFAULT 20,
    warehouse_name TEXT DEFAULT 'Ikeja Central Depot',
    shelve_location TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    warehouse_id BIGINT,
    movement_type TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    previous_quantity INTEGER NOT NULL,
    new_quantity INTEGER NOT NULL,
    reference_number TEXT,
    notes TEXT,
    recorded_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. ORDERS & COMMERCIAL SALES
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    order_number TEXT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    sales_agent_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(15,2) DEFAULT 0,
    vat_amount NUMERIC(15,2) DEFAULT 0,
    total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
    payment_status TEXT NOT NULL DEFAULT 'UNPAID',
    payment_method TEXT DEFAULT 'Bank Transfer',
    delivery_status TEXT NOT NULL DEFAULT 'PENDING',
    order_date DATE DEFAULT CURRENT_DATE,
    approved_by BIGINT,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(15,2) NOT NULL,
    total_price NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    agent_id BIGINT,
    order_id BIGINT,
    amount NUMERIC(15,2) NOT NULL,
    payment_method TEXT DEFAULT 'Bank Transfer',
    reference_number TEXT,
    status TEXT DEFAULT 'PAID',
    payment_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    driver_name TEXT,
    driver_phone TEXT,
    vehicle_number TEXT,
    dispatch_time TIMESTAMPTZ,
    actual_delivery_time TIMESTAMPTZ,
    delivery_status TEXT DEFAULT 'PENDING',
    recipient_name TEXT,
    recipient_signature TEXT,
    proof_of_delivery_photo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. VISITS & MERCHANDISING
CREATE TABLE IF NOT EXISTS public.visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    agent_id BIGINT NOT NULL,
    customer_id BIGINT,
    store_id BIGINT,
    status TEXT DEFAULT 'PLANNED',
    planned_date DATE DEFAULT CURRENT_DATE,
    planned_time TIMESTAMPTZ,
    actual_arrival TIMESTAMPTZ,
    actual_departure TIMESTAMPTZ,
    duration_minutes INTEGER DEFAULT 0,
    check_in_lat NUMERIC(10,7),
    check_in_lng NUMERIC(10,7),
    is_geofence_verified BOOLEAN DEFAULT FALSE,
    visit_purpose TEXT,
    shelf_share_percent NUMERIC(5,2),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.visit_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    visit_id BIGINT NOT NULL REFERENCES public.visits(id) ON DELETE CASCADE,
    person_met TEXT,
    visit_outcome TEXT,
    sales_status TEXT,
    customer_feedback TEXT,
    competitor_activity TEXT,
    stock_availability TEXT,
    issues_identified TEXT,
    order_created BOOLEAN DEFAULT FALSE,
    order_id BIGINT,
    follow_up_required BOOLEAN DEFAULT FALSE,
    follow_up_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. SMART SHIFT ATTENDANCE & TELEMETRY
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    clock_in TIMESTAMPTZ,
    clock_in_time TIMESTAMPTZ,
    clock_out TIMESTAMPTZ,
    clock_out_time TIMESTAMPTZ,
    morning_clock_in TIMESTAMPTZ,
    midday_clock_in TIMESTAMPTZ,
    evening_clock_out TIMESTAMPTZ,
    clock_in_latitude NUMERIC(10,7),
    clock_in_longitude NUMERIC(10,7),
    clock_out_latitude NUMERIC(10,7),
    clock_out_longitude NUMERIC(10,7),
    clock_in_address TEXT,
    clock_out_address TEXT,
    clock_in_accuracy NUMERIC,
    distance_meters NUMERIC,
    geofence_radius INTEGER DEFAULT 150,
    is_geofence_verified BOOLEAN DEFAULT TRUE,
    is_override BOOLEAN DEFAULT FALSE,
    override_reason TEXT,
    override_by TEXT,
    working_hours NUMERIC(6,2) DEFAULT 0,
    working_duration_text TEXT DEFAULT '0h 00m',
    status TEXT NOT NULL DEFAULT 'Present',
    attendance_type TEXT DEFAULT 'STAFF_CLOCK_IN',
    activity TEXT DEFAULT 'Staff Clock-In',
    is_late BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT attendance_employee_date_unique UNIQUE(employee_id, date)
);

CREATE TABLE IF NOT EXISTS public.location_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    employee_name TEXT,
    role TEXT,
    company_id BIGINT DEFAULT 1,
    supervisor_id BIGINT,
    store_id BIGINT,
    location_id BIGINT,
    assigned_market TEXT,
    assigned_region TEXT,
    assigned_state TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    server_timestamp TIMESTAMPTZ DEFAULT NOW(),
    local_time_lagos TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    accuracy NUMERIC,
    address TEXT,
    current_activity TEXT,
    activity TEXT,
    attendance_type TEXT,
    attendance_id BIGINT,
    is_inside_geofence BOOLEAN DEFAULT TRUE,
    distance_from_store NUMERIC,
    geofence_status TEXT,
    status TEXT DEFAULT 'success',
    battery_level INTEGER DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.location_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    supervisor_id BIGINT,
    company_id BIGINT DEFAULT 1,
    alert_type TEXT NOT NULL,
    severity TEXT DEFAULT 'warning',
    message TEXT NOT NULL,
    details JSONB,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. TASKS & LEAVE REQUESTS
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    assigned_to BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    assigned_by BIGINT,
    client_name TEXT,
    project_name TEXT,
    requires_client_dispatch BOOLEAN DEFAULT FALSE,
    sent_to_client BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'pending',
    priority TEXT DEFAULT 'medium',
    due_date TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    leave_type TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days INTEGER NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending',
    approved_by BIGINT,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT DEFAULT 1,
    user_id BIGINT,
    user_email TEXT,
    action TEXT NOT NULL,
    entity TEXT,
    entity_id TEXT,
    previous_value JSONB,
    new_value JSONB,
    ip_address TEXT,
    device TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================================================
-- 13. SEED FOUNDATIONAL COMPANY, SETTINGS, DEPARTMENTS & 8 CANONICAL ACCOUNTS
-- ==============================================================================

INSERT INTO public.companies (id, name, business_type, industry, registration_number, email, phone, address, country, state, city, status)
VALUES (1, 'Nexfeild', 'FMCG Wholesale & Retail Distribution', 'Consumer Goods & Retail', 'RC-1849201', 'operations@nexfeild.ng', '+2348006393435', 'Plot 12, Commercial Avenue, Ikeja Industrial Estate, Lagos', 'Nigeria', 'Lagos', 'Ikeja', 'active')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO public.company_settings (id, company_id, receipt_company_name, receipt_tagline, receipt_title, receipt_address, receipt_phone, receipt_footer_note)
VALUES (1, 1, 'EXPERIENTIAL EDGE', 'Integrated Marketing & Commercial Distribution Solutions', 'EDGEWFORCE SALES RECEIPT', 'Plot 12, Commercial Avenue, Ikeja Industrial Estate, Lagos, Nigeria', '+2348006393435', 'Goods received in good condition are not returnable after 48 hours. Thank you for your business!')
ON CONFLICT (company_id) DO NOTHING;

INSERT INTO public.departments (id, name, code, description) VALUES
(1, 'Commercial Sales', 'SALES', 'Retail distribution, merchant network & key accounts'),
(2, 'Field Operations', 'FIELD', 'Route execution, store audits & merchandising'),
(3, 'Human Resources', 'HR', 'People operations & workforce management'),
(4, 'Finance & Accounts', 'FINANCE', 'Treasury, audit, collections & payroll'),
(5, 'Technology & IT', 'TECH', 'Platform administration, cybersecurity & telemetry'),
(6, 'Executive Management', 'EXEC', 'Executive leadership & corporate governance')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.ranks (id, code, name, level, active) VALUES
(1, 'CEO', 'Chief Executive Officer', 1, TRUE),
(2, 'IT_ADMIN', 'IT Super Admin / Portal Administrator', 1, TRUE),
(3, 'CTO', 'Chief Technology Officer', 2, TRUE),
(4, 'HR', 'Head of Human Resources', 3, TRUE),
(5, 'SENIOR_ACCOUNTANT', 'Head of Accounting & Payroll', 4, TRUE),
(6, 'ACCOUNTANT', 'Accountant', 5, TRUE),
(7, 'MANAGER', 'Regional Manager', 6, TRUE),
(8, 'SUPERVISOR', 'Field Operations Supervisor', 7, TRUE),
(9, 'STAFF', 'Operations Staff', 8, TRUE)
ON CONFLICT (code) DO NOTHING;

-- INSERT THE EXACT 8 DEFAULT DEPARTMENT ACCOUNTS (Password: ChangeMe123!)
-- Hash: $2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v
INSERT INTO public.users (id, company_id, full_name, email, password_hash, phone, role_code, status) VALUES
(1, 1, 'IT Super Admin', 'it@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348000000001', 'SUPER_ADMIN', 'active'),
(2, 1, 'Chief Executive Officer', 'ceo@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348000000002', 'CEO', 'active'),
(3, 1, 'Head of Human Resources', 'hr@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348000000003', 'HR_MANAGER', 'active'),
(4, 1, 'Commercial Sales Lead', 'sales@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348031234567', 'SALES_AGENT', 'active'),
(5, 1, 'Field Operations Lead', 'field@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348029876543', 'FIELD_AGENT', 'active'),
(6, 1, 'Finance & Accounting Lead', 'accountant@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348000000006', 'ACCOUNTANT', 'active'),
(7, 1, 'Field Operations Supervisor', 'supervisor@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348187654321', 'SUPERVISOR', 'active'),
(8, 1, 'Corporate Operations Staff', 'staff@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348145550192', 'STAFF_MEMBER', 'active'),
(9, 1, 'Platform Super Administrator', 'admin@edgewforce.com', '$2a$10$wE9UfUa8sM3Z.Yp2T5mH5uL6L1F9n2d8Y2W8Z9V4p1Q2r3S4t5u6v', '+2348000000000', 'SUPER_ADMIN', 'active')
ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, role_code = EXCLUDED.role_code;

INSERT INTO public.employees (id, company_id, user_id, employee_code, first_name, last_name, phone, department_id, department, position, territory, supervisor_id, rank_code, base_salary, status) VALUES
(1, 1, 1, 'EMP-1001', 'IT Admin', 'Service', '+2348000000001', 5, 'Technology & IT', 'IT Super Admin / System Engineer', 'Headquarters', NULL, 'IT_ADMIN', 1800000, 'active'),
(2, 1, 2, 'EMP-1002', 'Executive', 'Management', '+2348000000002', 6, 'Executive Management', 'Chief Executive Officer', 'National', NULL, 'CEO', 2500000, 'active'),
(3, 1, 3, 'EMP-1003', 'HR', 'Manager', '+2348000000003', 3, 'Human Resources', 'Head of Human Resources', 'Headquarters', NULL, 'HR', 1200000, 'active'),
(4, 1, 4, 'EMP-1004', 'Thompson', 'Babatunde', '+2348031234567', 1, 'Commercial Sales', 'Senior Commercial Sales Agent', 'Lagos Mainland', 7, 'STAFF', 380000, 'active'),
(5, 1, 5, 'EMP-1005', 'Godfrey', 'Okorie', '+2348029876543', 2, 'Field Operations', 'Field Operations Lead Agent', 'Lagos Island & Lekki', 7, 'STAFF', 350000, 'active'),
(6, 1, 6, 'EMP-1006', 'Finance', 'Officer', '+2348000000006', 4, 'Finance & Accounts', 'Head of Accounting & Payroll', 'Headquarters', NULL, 'ACCOUNTANT', 1100000, 'active'),
(7, 1, 7, 'EMP-1007', 'Amina', 'Bello', '+2348187654321', 2, 'Field Operations', 'Field Operations Supervisor', 'Lagos Island', NULL, 'SUPERVISOR', 750000, 'active'),
(8, 1, 8, 'EMP-1008', 'Gloria', 'Iwuh', '+2348145550192', 3, 'Corporate Operations', 'Workforce Operations Analyst', 'Headquarters', 3, 'STAFF', 420000, 'active'),
(9, 1, 9, 'EMP-1009', 'Platform', 'Administrator', '+2348000000000', 6, 'Executive Governance', 'Super Administrator', 'National', NULL, 'CEO', 1800000, 'active')
ON CONFLICT (employee_code) DO NOTHING;

-- Default Locations
INSERT INTO public.work_locations (id, company_id, name, location_type, address, state, city, latitude, longitude, geofence_radius, geofence_radius_meters, status) VALUES
(1, 1, 'Lagos Victoria Island Office', 'Office', '14B Idowu Martins St, Victoria Island', 'Lagos', 'Victoria Island', 6.4281000, 3.4219000, 150, 150, 'active'),
(2, 1, 'Ikeja Central Distribution Depot', 'Depot', 'Plot 12 Commercial Ave, Ikeja Industrial', 'Lagos', 'Ikeja', 6.5984000, 3.3524000, 200, 200, 'active'),
(3, 1, 'Abuja Central Hub', 'Branch', 'Plot 44 Ahmadu Bello Way, Central Area', 'FCT Abuja', 'Abuja', 9.0765000, 7.3986000, 150, 150, 'active')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.employee_location_assignments (company_id, employee_id, location_id, assignment_type, is_primary, is_active) VALUES
(1, 1, 1, 'primary', TRUE, TRUE),
(1, 2, 1, 'primary', TRUE, TRUE),
(1, 3, 1, 'primary', TRUE, TRUE),
(1, 4, 2, 'primary', TRUE, TRUE),
(1, 5, 1, 'primary', TRUE, TRUE),
(1, 6, 1, 'primary', TRUE, TRUE),
(1, 7, 1, 'primary', TRUE, TRUE),
(1, 8, 1, 'primary', TRUE, TRUE),
(1, 9, 1, 'primary', TRUE, TRUE)
ON CONFLICT DO NOTHING;
ON CONFLICT DO NOTHING;
