// ==============================================================================
// EDGEWFORCE - AUTHORITATIVE STAFF DATASET & IDEMPOTENT IMPORT SERVICE
// Imports all 58 corporate staff records with deduplication, multi-identifier
// auth account creation, field normalization, and HR review flagging.
// ==============================================================================

import bcrypt from 'bcryptjs';
import { db } from '../config/database.js';
import { normalizePhone, normalizeEmail, isEmail } from '../utils/phoneNormalizer.js';
import { logger } from '../utils/logger.js';

// The authoritative raw staff dataset
export const AUTHORITATIVE_STAFF_DATASET = [
  {
    name: "Olasode Olawale",
    email: "Oolasode@m.experiential-edge.com",
    dob: "6/19/1993",
    marital_status: "Married",
    address: "9 Paseda idi oya ibadan",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "9 paseda street idi oya",
    city_lga: "Ibadan",
    state_origin_residence: "Oyo",
    work_email: "Oolasode@m.experiential-edge.com",
    phone: "07037924201",
    emergency_contact: "Deborah",
    emergency_relationship: "Wife",
    emergency_phone: "08102649646",
    job_title: "CTO",
    department: "IT",
    date_joined: "9/23/2022",
    work_location: "Maryland",
    supervisor: "Vivian Osigweh",
    blood_group: "As",
    bank_name: "Opay",
    account_number: "7037924201",
    hobbies: null,
    landmark: "Living proof supermarket"
  },
  {
    name: "Lucky Loveday",
    email: "LOVEDAYOPUS@GMAIL.COM",
    dob: "10/19/1993",
    marital_status: "Single",
    address: "1 U gonna Street off Utility street Bako Estate, Irawo Mile 12",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "1 U gonna Street off Utility street Bako Estate, Irawo Mile 12",
    city_lga: "Kosofe",
    state_origin_residence: "Rivers/ Lagos",
    work_email: "lloveday@m.experiential-edge.com",
    phone: "08143692166",
    emergency_contact: "08063296220",
    emergency_relationship: "Sister",
    emergency_phone: "08063296220",
    job_title: "Capability and operations manager",
    department: "HR",
    date_joined: "5/19/2025",
    work_location: "Maryland",
    supervisor: "MD",
    blood_group: null,
    bank_name: "Access",
    account_number: "0725197366",
    hobbies: null,
    landmark: "Irawo Busstop"
  },
  {
    name: "Deborah Obadina",
    email: "deborahobadina01@gmail.com",
    dob: "6/5/1987",
    marital_status: "Married",
    address: "34 Greenland street egbeda",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "34 Greenland street egbeda",
    city_lga: "Alimosho",
    state_origin_residence: "Lagos",
    work_email: "dobadina@m.experiential-edge.com",
    phone: "08139203775",
    emergency_contact: "Dare otujinrin",
    emergency_relationship: "Brother",
    emergency_phone: "07030746413",
    job_title: "Account executive",
    department: "Strategy",
    date_joined: "7/24/2025",
    work_location: "Maryland",
    supervisor: "Mrs Chidinma",
    blood_group: null,
    bank_name: "Sterling bank",
    account_number: "0107337280",
    hobbies: null,
    landmark: "Egbeda"
  },
  {
    name: "Egbewole Adewole Kayode",
    email: "egbewoleak@yahoo.com",
    dob: "9/28/1984",
    marital_status: "Married",
    address: "49, Adebowale Crescent Ago 40 Estate Aboru",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "49, Adebowale Crescent Ago 40 Estate Aboru",
    city_lga: "Alimosho",
    state_origin_residence: "Osun/Lagos",
    work_email: "a.egbewole@m.experiential-edge.com",
    phone: "08066473194",
    emergency_contact: "Egbewole Olubunmi",
    emergency_relationship: "Spouse",
    emergency_phone: "07031510725",
    job_title: "Compliance Manager",
    department: "Operation",
    date_joined: "2/14/2024",
    work_location: "Lagos",
    supervisor: "Mrs Vivian Osigweh (MD)",
    blood_group: "AA",
    bank_name: "First Bank",
    account_number: "3057047291",
    hobbies: "Traveling",
    landmark: "Nepa Office Ago 40"
  },
  {
    name: "MARVELLOUS DANIEL-OKE",
    email: "thegreatmarvellousoke@gmail.com",
    dob: "2/4/2001",
    marital_status: "Single",
    address: "57, HARRISON SOLACE, AGO PALACE WAY, OKOTA, LAGOS",
    nationality: "NIGERIAN",
    staff_id: null,
    home_address: "57, HARRISON SOLACE, AGO PALACE WAY, OKOTA, LAGOS",
    city_lga: "LAGOS/OSHODI ISOLO",
    state_origin_residence: "OYO/LAGOS",
    work_email: "moke@m.experiential-edge",
    phone: "09041430470",
    emergency_contact: "PRAISE OLAJIDE",
    emergency_relationship: "SIBLING",
    emergency_phone: "08181475532",
    job_title: "COMPLIANCE MANAGER",
    department: "COMPLIANCE",
    date_joined: "11/1/2025",
    work_location: "MARYLAND",
    supervisor: "KAYODE",
    blood_group: "O+",
    bank_name: "WEMA",
    account_number: "0410169087",
    hobbies: null,
    landmark: "OKOTA"
  },
  {
    name: "Ajiboye Taiwo Olayemi",
    email: "ajiboyetayeolayemi2018@gmail.com",
    dob: "5/12/1999",
    marital_status: "Single",
    address: "6, dapo sokeye close isolo Lagos",
    nationality: "Nigerian",
    staff_id: "019",
    home_address: "6, dapo sokeye close isolo Lagos",
    city_lga: "Lagos",
    state_origin_residence: "Osun state",
    work_email: "tajiboye@m.experiential-edge.com",
    phone: "09133313366",
    emergency_contact: "07087579977",
    emergency_relationship: "Twin brother",
    emergency_phone: "09133313366",
    job_title: "Compliance Officer",
    department: "Operations",
    date_joined: "1/5/2025",
    work_location: "Merryland",
    supervisor: "Mr. Kayode",
    blood_group: "AA",
    bank_name: "Ajiboye Taye",
    account_number: "2119602047",
    hobbies: "Listening to sermon",
    landmark: "Isolo"
  },
  {
    name: "Makinde Shadiat Temitope",
    email: "tmakinde@m.experiential-edge.com",
    dob: "9/21/1997",
    marital_status: "Single",
    address: "2,Ganiu lawal street",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "2,Ganiu lawal street moricas",
    city_lga: "Alimosho LGA Lagos state",
    state_origin_residence: "Ogun state/Lagos state",
    work_email: "tmakinde@m.experiential-edge.com",
    phone: "08103769573",
    emergency_contact: "09024413790",
    emergency_relationship: "Mother",
    emergency_phone: "08103769573",
    job_title: "Compliance officer",
    department: "Compliance department",
    date_joined: "8/11/2025",
    work_location: "15,Atiba Osborne Mende Maryland",
    supervisor: "Mr kayode Adewole Egbewole",
    blood_group: "0 positive",
    bank_name: "Makinde shadiat Temitope",
    account_number: "0065791380",
    hobbies: "Planing and organizing, Problem-solving, Leading teams, Tracking progress, Cooking",
    landmark: "Idimu bustop"
  },
  {
    name: "Adeyeye oluwatoyosi Adedamola",
    email: "adeyeyeoluwatoyosi2000@gmail.com",
    dob: "9/23/2000",
    marital_status: "Single",
    address: "No 1 tiwalade close bamisile estate",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "No 1 tiwalade close bamisile estate",
    city_lga: "Lagos",
    state_origin_residence: "Ekiti",
    work_email: "Oadeyeye@m.experiential-edge.com",
    phone: "08134505006",
    emergency_contact: "07066420768",
    emergency_relationship: "Sister",
    emergency_phone: "07066420768",
    job_title: "Compliance manager",
    department: "Compliance",
    date_joined: "9/25/2025",
    work_location: "Lagos",
    supervisor: "Kayode",
    blood_group: null,
    bank_name: "UBA",
    account_number: "2386993514",
    hobbies: "Reading",
    landmark: "Ikeja"
  },
  {
    name: "Oyewumi Olukunle",
    email: "kunleoyewumi@gmail.com",
    dob: "3/6/1970",
    marital_status: "Married",
    address: "12, Toyin crescent,Giwa",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "12,Toyin Crescent Giwa",
    city_lga: "Ifako-Ijaye",
    state_origin_residence: "Osun",
    work_email: "koyewumi@m.experiential-edge.com",
    phone: "08033830324",
    emergency_contact: "Oyewumi Omolara",
    emergency_relationship: "Wife",
    emergency_phone: "08028103335",
    job_title: "Compliant Manager",
    department: "Operations",
    date_joined: "9/9/2024",
    work_location: "Maryland",
    supervisor: "Chidinma Nwaeze",
    blood_group: "O",
    bank_name: "FCMB",
    account_number: "0737 460 024",
    hobbies: "Music/singing/movies",
    landmark: "Bokuu at Giwa Bus stop"
  },
  {
    name: "Owotomo kehinde iromidayo",
    email: "owotomokenny@gmail.com",
    dob: "7/21/1987",
    marital_status: "Married",
    address: "Opposite omotayo hospital ososami oke ado ibadan",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Opposite omotayo hospital ososami oke ado",
    city_lga: "Ibadan",
    state_origin_residence: "Ondo/oyo",
    work_email: "K.owotomo@m.experiential-edge.com",
    phone: "08067505695",
    emergency_contact: "08104794831",
    emergency_relationship: "Wife",
    emergency_phone: "08104794831",
    job_title: "Compliance manager",
    department: "Opration",
    date_joined: "3/8/2024",
    work_location: "Lagos",
    supervisor: "Egbeleye Kayode",
    blood_group: "O+",
    bank_name: "First bank",
    account_number: "3134107490",
    hobbies: "Reading, sport",
    landmark: "Ososami"
  },
  {
    name: "ONYEKACHI STELLA",
    email: "KACHIELLA9@GMAIL.COM",
    dob: "9/8/1997",
    marital_status: "Single",
    address: "NO 10 INFINITY CLOSE FESTAC TOWN LAGOS",
    nationality: "NIGERIAN",
    staff_id: "003",
    home_address: "NO 10 INFINITY CLOSE FESTAC TOWN LAGOS",
    city_lga: "MAINLAND /LAGOS",
    state_origin_residence: "ANAMBRA/LAGOS",
    work_email: "s.onyekachi@m.experiential-edge.com",
    phone: "08148860221",
    emergency_contact: "08033438046",
    emergency_relationship: "FATHER",
    emergency_phone: "08033438046",
    job_title: "COMPLIANCE MANAGER",
    department: "COMPLAINCE/OERATIONS",
    date_joined: "8/21/2023",
    work_location: "IKEJA",
    supervisor: "MR KAYODE",
    blood_group: "A+",
    bank_name: "FIDELITY",
    account_number: "6550101694",
    hobbies: "NIL",
    landmark: "6TH AVENUE"
  },
  {
    name: "AKINOLA OPEYEMI FLORENCE",
    email: "akinolaopeyemi158@gmail.com",
    dob: "2/18/1995",
    marital_status: "Single",
    address: "7 JIDE AKINOLA CLOSE AGBELEKALE",
    nationality: "NIGERIA",
    staff_id: "014",
    home_address: "7 JIDE AKINOLA CLOSE AGBELEKALE",
    city_lga: "LAGOS",
    state_origin_residence: null,
    work_email: "Fakinola@m.experiential-edge.com",
    phone: "08142880478",
    emergency_contact: "09032106013",
    emergency_relationship: "sister",
    emergency_phone: "08142880478",
    job_title: "FINANCE MANAGER",
    department: "FINANCE",
    date_joined: "1/13/2025",
    work_location: "MARYLAND",
    supervisor: "MR ID",
    blood_group: "O+",
    bank_name: "GTBANK",
    account_number: "0156304321",
    hobbies: "SURFING THE INTERNET",
    landmark: "ABULE-EGBA"
  },
  {
    name: "Izuchukwu Valentine Nworah",
    email: "valentine.nworah@gmail.com",
    dob: "9/4/1989",
    marital_status: "Single",
    address: "No 3 Adewale Balogun street, Powerline Busstop",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No 3 Adewale Balogun street, Powerline Busstop",
    city_lga: "Isheri Alimosho",
    state_origin_residence: "Anambra/ Lagos",
    work_email: "valentine.nworah@gmail.com",
    phone: "08060720372",
    emergency_contact: "Nworah Stella",
    emergency_relationship: "Mom",
    emergency_phone: "08064722991",
    job_title: "VSR and Operations Manager",
    department: "Operations",
    date_joined: "1/21/2026",
    work_location: "Ogba",
    supervisor: "Mrs. Vivian Osigweh",
    blood_group: "A+",
    bank_name: "Sterling Bank",
    account_number: "0036406994",
    hobbies: null,
    landmark: "Powerline Busstop"
  },
  {
    name: "Samuel Oyegbade",
    email: "Ohluwatosin@gmail.com",
    dob: "8/4/1993",
    marital_status: "Married",
    address: "8, Church Close, Olaniyi Abule Egba",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "8, Church Close, Olaniyi Abule Egba",
    city_lga: "Ifako Ijaye",
    state_origin_residence: "Lagos",
    work_email: "S.tosin@m.experiential-edge.com",
    phone: "08106156569",
    emergency_contact: "09039653051",
    emergency_relationship: "Wife",
    emergency_phone: "09039653051",
    job_title: "Operations Executive",
    department: "Operations",
    date_joined: "5/7/2024",
    work_location: "Lagos",
    supervisor: "Mr Oluwatoyin",
    blood_group: null,
    bank_name: "Gtbank",
    account_number: "0136824120",
    hobbies: null,
    landmark: "Ijaye"
  },
  {
    name: "Patricia Dare",
    email: "darepatricia28@gmail.com",
    dob: "12/28/1993",
    marital_status: "Single",
    address: "Beach Area, Nsukka Enugu State",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Beach Area Nsukka, Enugu State",
    city_lga: "Nsukka",
    state_origin_residence: "Osun",
    work_email: null,
    phone: "08147382457",
    emergency_contact: "08062208071",
    emergency_relationship: "Aunty",
    emergency_phone: "08062208071",
    job_title: "Compliance manager",
    department: "Compliance",
    date_joined: "9/8/2025",
    work_location: "Eastern region",
    supervisor: "Mr Kayode",
    blood_group: "AB+",
    bank_name: "First Bank",
    account_number: "3098285540",
    hobbies: "Singing, cooking",
    landmark: "Oke odo area,Ejigbo"
  },
  {
    name: "Asukwo Richard",
    email: "richard.asukwo21@gmail.com",
    dob: "5/21/1985",
    marital_status: "Single",
    address: "No 16, Okunu Odunuegbe street, Adexson Ilepo bus stop, Akesan, igando, Lagos.",
    nationality: "Nigerian",
    staff_id: "005",
    home_address: "No 16, Okunu Odunuegbe street, Adexson Ilepo bus stop, Akesan.igando,lagos",
    city_lga: "Alimosho",
    state_origin_residence: "Akwa ibom",
    work_email: "richard.asukwo21@gmail.com",
    phone: "08135032689",
    emergency_contact: "08063114785",
    emergency_relationship: "Brother",
    emergency_phone: "08063114785",
    job_title: "Operation Manger",
    department: "Operations",
    date_joined: "11/1/2024",
    work_location: "Operations",
    supervisor: "Manager",
    blood_group: "O+",
    bank_name: "UBA",
    account_number: "2056557615",
    hobbies: "Sport, reading and travelling",
    landmark: "Adexon ile-epo bistop"
  },
  {
    name: "Godfrey Okorie",
    email: "gokoriee@gmail.com",
    dob: "12/2/1988",
    marital_status: "Married",
    address: "Road 1 house 19 diamond estate igando road",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "Road 1 house 19 diamond estate igando road",
    city_lga: "Lagos",
    state_origin_residence: "Cross river",
    work_email: "gokorie.m@experiential-edge.com",
    phone: "07050956271",
    emergency_contact: "07054077721",
    emergency_relationship: "Spouse",
    emergency_phone: "08029589181",
    job_title: "Senior operations manager",
    department: "Operations",
    date_joined: "4/2/2017",
    work_location: "Maryland",
    supervisor: "Chidinma Nwaeze",
    blood_group: null,
    bank_name: "Parallex bank",
    account_number: "2000388990",
    hobbies: null,
    landmark: "Diamond estate bstp"
  },
  {
    name: "Owolebi Ayomipo",
    email: "owolebiayomipo@gmail.com",
    dob: "8/7/1996",
    marital_status: "Single",
    address: "72, buari street, ogudu, Ojota, Lagos, Nigeria.",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "72, buari street, ogudu, ojota, lagos",
    city_lga: "Kosofe",
    state_origin_residence: "Lagos",
    work_email: "aowolebi@m.experiential-edge.com",
    phone: "08027208651",
    emergency_contact: "Owolebi Victor",
    emergency_relationship: "brother",
    emergency_phone: "+234 805 339 7016",
    job_title: "Graphic designer",
    department: "Creative",
    date_joined: "1/14/2025",
    work_location: "office",
    supervisor: "Gloria Iwuh",
    blood_group: "O",
    bank_name: "Owolebi Ayomipo",
    account_number: "2069581014",
    hobbies: "Art",
    landmark: "Ojota"
  },
  {
    name: "Esu Lynda",
    email: "esulynda88@gmail.com",
    dob: "10/14/1997",
    marital_status: "Single",
    address: "12 Olanipekun Street Ogba",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "12 Olanipekun Street Ogba",
    city_lga: "Ikeja",
    state_origin_residence: "Lagos",
    work_email: "lynda@edgedirect2u.com.ng",
    phone: "07064290635",
    emergency_contact: "+234 706 273 8052",
    emergency_relationship: "Sister",
    emergency_phone: "+234 706 273 8052",
    job_title: "Senior Finance Manager",
    department: "Finance",
    date_joined: "1/2/2023",
    work_location: "Ogba",
    supervisor: "MD",
    blood_group: "AB+",
    bank_name: "UBA",
    account_number: "2115115963",
    hobbies: "Financial analysis, budgeting, exploring ways to optimize business operations, studying market trends, personal finance strategies.",
    landmark: "Aguda"
  },
  {
    name: "Adebisi Adeyinka Olalekan",
    email: "adebysee2018@gmail.com",
    dob: "5/15/1967",
    marital_status: "Married",
    address: "3B, New World Street, Fatade Estate Ijegun, Lagos",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "3b, New World Street, Fatade Estate Ijegun Lagos",
    city_lga: "Alimosho",
    state_origin_residence: "Ekiti/Lagos",
    work_email: "adebysee2018@gmail.com",
    phone: "08034540406",
    emergency_contact: "Adebisi Biliqis Olayiwola",
    emergency_relationship: "Wife",
    emergency_phone: "08029756204",
    job_title: "Warehouse Manager",
    department: "E-EDGE DIRECT 2 YOU",
    date_joined: "2/3/2025",
    work_location: "Ibadan",
    supervisor: "Maryjane",
    blood_group: null,
    bank_name: "First Bank Nig. Plc",
    account_number: "2000531375",
    hobbies: "Football",
    landmark: "Estate Junction"
  },
  {
    name: "Osere Juliana merciful",
    email: "jullyosere22456@gmail.com",
    dob: "7/19/2000",
    marital_status: "Single",
    address: "15, soroga street, jumofak bustop ikorodu",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "15,soroga street, jumofak bustop ikorodu",
    city_lga: "Ikorodu",
    state_origin_residence: "Edo state",
    work_email: "jullyosere22456@gmail.com",
    phone: "07061137500",
    emergency_contact: "09065992314",
    emergency_relationship: "Mother",
    emergency_phone: "09169464791",
    job_title: "Receptionist",
    department: "Admin",
    date_joined: "1/12/2026",
    work_location: "15,atiba orsborne street",
    supervisor: "Mr Adedoyin",
    blood_group: "O+",
    bank_name: "GtBank",
    account_number: "0451963926",
    hobbies: "Movies",
    landmark: null
  },
  {
    name: "Adeyemi Vivian",
    email: "adeyemivivianomon@gmail.com",
    dob: "10/9/1976",
    marital_status: "Married",
    address: "No 9 mustapha street celeapatha Ayobo",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No 9 mustapha street celeapatha Ayobo",
    city_lga: "Lagos/ Alimosho",
    state_origin_residence: "Edo state",
    work_email: "adeyemivivianomon@gmail.com",
    phone: "08060815356",
    emergency_contact: "Adeyemi oluwaseyi",
    emergency_relationship: "Son",
    emergency_phone: "07067186206",
    job_title: "Chief / ware house manager",
    department: "Chief",
    date_joined: "5/24/2023",
    work_location: "Maryland",
    supervisor: "Osigwe Vivian",
    blood_group: "O +",
    bank_name: "First bank",
    account_number: "3048650541",
    hobbies: "Cooking,singing and reading",
    landmark: "So east"
  },
  {
    name: "Nwaeze Chidinma",
    email: "cnwaeze@experiential-edge.com",
    dob: "4/9/1988",
    marital_status: "Married",
    address: "Block 73, flat 4, Jakande Estate, Oke-Afa",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Block 73, Flat 4, Jakande Estate, Oke-Afa",
    city_lga: "Lagos/Oshodi-Isolo",
    state_origin_residence: "Lagos",
    work_email: "cnwaeze@experiential-edge.com",
    phone: "08066693700",
    emergency_contact: "Uchenna Nwaeze",
    emergency_relationship: "Husband",
    emergency_phone: "08104715159",
    job_title: "Senior Strategy and Communication Manager",
    department: "Strategy",
    date_joined: "2/3/2023",
    work_location: "Maryland",
    supervisor: "Gloria Iwuh",
    blood_group: null,
    bank_name: "Access Bank",
    account_number: "0033721742",
    hobbies: null,
    landmark: null
  },
  {
    name: "Okorie kemi",
    email: "sophiaokoriee@gmail.com",
    dob: "10/16/1994",
    marital_status: "Married",
    address: "Road1house 19 diamond estate isheri igando",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "Road1 house 19 diamond estate isheri Igando",
    city_lga: "Alimosho local government",
    state_origin_residence: "Lagos state",
    work_email: "Sophiaokoriee@gmail.com",
    phone: "07054077721",
    emergency_contact: "Okorie Godfrey",
    emergency_relationship: "Husband",
    emergency_phone: "07050956271",
    job_title: "Procurement",
    department: "Procurement",
    date_joined: "11/16/2025",
    work_location: "Maryland Lagos state",
    supervisor: "Dr Ann ogri",
    blood_group: null,
    bank_name: "Okorie Sophia ajoke",
    account_number: "2135459924",
    hobbies: "Swimming",
    landmark: "Isheri bus-stop"
  },
  {
    name: "Ekeocha Ebube Christiana",
    email: "nicoleekeocha@gmail.com",
    dob: "4/19/1997",
    marital_status: "Single",
    address: "15, Prince Jamaica street, Egan-Igando, Lagos.",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "15, Prince Jamaica street, Egan-Igando, Lagos",
    city_lga: "Alimosho",
    state_origin_residence: "Lagos State",
    work_email: "cekeocha@m.experiential-edge.com",
    phone: "09034043158",
    emergency_contact: "Mrs. Veronica Ekeocha",
    emergency_relationship: "Mother",
    emergency_phone: "08033614958",
    job_title: "Senior Strategy and Account Manager",
    department: "Strategy and Communication",
    date_joined: "7/14/2025",
    work_location: "Maryland",
    supervisor: "Line Manager - Ms. Gloria Iwuh. However, I receive directives from Mrs. Chidinma Nwaeze too.",
    blood_group: "O+",
    bank_name: "Stanbic Ibtc",
    account_number: "0059294215",
    hobbies: "Reading, learning new skills and listening to music",
    landmark: "Igando BRT busstop"
  },
  {
    name: "Albert Rhema",
    email: "remy.bertt@gmail.com",
    dob: "12/7/1999",
    marital_status: "Single",
    address: "4, Bisiriyu Lawal Street, Jaiyeoba, Shasha",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "4, Bisiriyu Lawal Street, Jaiyeoba, Shasha",
    city_lga: "Lagos",
    state_origin_residence: "Lagos",
    work_email: "arhema@m.experential-edge.com",
    phone: "07032416493",
    emergency_contact: "07036300971",
    emergency_relationship: "Mother",
    emergency_phone: "07036300971",
    job_title: "Business Development Strategist",
    department: "Strategy",
    date_joined: "12/8/2025",
    work_location: "Onsite",
    supervisor: "Ms. Chidinma Nwaeze",
    blood_group: null,
    bank_name: "GTBank",
    account_number: "0470317241",
    hobbies: "Reading, Learning, Singing, Business",
    landmark: "Jaiyeoba"
  },
  {
    name: "Tochukwu Okonta",
    email: "tokonta@m.experiential-edge.com",
    dob: "8/17/1993",
    marital_status: "Single",
    address: "Ejigbo",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "8 Jimoh Oke",
    city_lga: "Ejigbo",
    state_origin_residence: "Delta",
    work_email: "tokonta@m.experiential-edge.com",
    phone: "08164809945",
    emergency_contact: "Grace ifeoma",
    emergency_relationship: "Sister",
    emergency_phone: "08028101028",
    job_title: "Strategist",
    department: "Strategy",
    date_joined: "6/3/1993",
    work_location: "Remote",
    supervisor: "Ms Gloria",
    blood_group: null,
    bank_name: "Zenith",
    account_number: "2468440950",
    hobbies: null,
    landmark: "NNPC"
  },
  {
    name: "Feyifoluwa Oluwatosin",
    email: "oluwatosinfeyifoluwa16@gmail.com",
    dob: "8/16/2002",
    marital_status: "Single",
    address: "10, Ogooluwa Ayanbode street, Oke-Ira, Ogba, Lagos.",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "10, Ogooluwa Ayanbode street, Oke-Ira, Ogba, Lagos.",
    city_lga: "Lagos",
    state_origin_residence: "Ekiti state",
    work_email: "FEmmanuel@m.experiential-edge.com",
    phone: "08163722231",
    emergency_contact: "08033960838",
    emergency_relationship: "Mother",
    emergency_phone: "08033960838",
    job_title: "Business development strategist",
    department: "Strategy",
    date_joined: "12/1/2025",
    work_location: "9, Emmanuel Olorunfemi street off ajenifuja Street off college road ogba",
    supervisor: "Miss Glo",
    blood_group: null,
    bank_name: "Guaranty Trust Bank",
    account_number: "0559528171",
    hobbies: "Football",
    landmark: null
  },
  {
    name: "Oshipelu Onaolapo",
    email: "oayorinde@m.experiential-edge.com",
    dob: "10/26/2002",
    marital_status: "Single",
    address: "No. 2 Ogunsehinde street, ketu, Lagos.",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No. 2 Ogunsehinde street",
    city_lga: "Ketu",
    state_origin_residence: "Ogun/lagos",
    work_email: "oayorinde@m.experiential-edge.com",
    phone: "08130714369",
    emergency_contact: "08033333817",
    emergency_relationship: "Bro",
    emergency_phone: "08130714369",
    job_title: "Senior Strategy and Operations Manager",
    department: "Strategy",
    date_joined: "11/10/2025",
    work_location: "Maryland",
    supervisor: "Ms Glow",
    blood_group: "O+",
    bank_name: "Stanbic IBTC",
    account_number: "0040165476",
    hobbies: "Sleeping",
    landmark: "Tipper"
  },
  {
    name: "Samuel Adeolu Elijah",
    email: "samueladeolu1133@yahoo.com",
    dob: "4/12/1992",
    marital_status: "Married",
    address: "Road Safety",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Road Safety Ogbomosho",
    city_lga: "Ogbomosho South",
    state_origin_residence: "Oyo State",
    work_email: "adeolusamuel640@gmail.com",
    phone: "08142665143",
    emergency_contact: "Oyekale Timilehin",
    emergency_relationship: "Wife",
    emergency_phone: "08103148550",
    job_title: "Van Sales Rep",
    department: "Sales",
    date_joined: "2/1/2026",
    work_location: "Ognomosho",
    supervisor: "Mr Ayoola",
    blood_group: null,
    bank_name: "Zenith Bank plc",
    account_number: "2122564774",
    hobbies: "Business",
    landmark: "Road Safety junction"
  },
  {
    name: "Babatunde Badirudeen",
    email: "babatunde@edgedirect2u.com.ng",
    dob: "10/26/1995",
    marital_status: "Married",
    address: "Birmingham, UK",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "1, Goodman street",
    city_lga: "Birmingham",
    state_origin_residence: "Ogun state",
    work_email: "babatunde@edgedirect2u.com.ng",
    phone: "+44 7350 152791",
    emergency_contact: "Aderonke Badirudeen",
    emergency_relationship: "Wife",
    emergency_phone: "+44 7350 164925",
    job_title: "IT Manager",
    department: "Information Technology",
    date_joined: "11/27/2023",
    work_location: "Remote",
    supervisor: "MD",
    blood_group: null,
    bank_name: "Wema Bank",
    account_number: "0245946172",
    hobbies: null,
    landmark: null
  },
  {
    name: "Diepreye Desmond",
    email: "diepreyeyazzy@gmail.com",
    dob: "3/23/2002",
    marital_status: "Single",
    address: "Block 8 Flat 5 Airforce base shasha",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Block 8 Flat 5 Airforce base shasha",
    city_lga: "Lagos",
    state_origin_residence: "Bayelsa",
    work_email: "ddiepreye@m.experiential-edge.com",
    phone: "07054353032",
    emergency_contact: "Mrs Diepreye Dinipere",
    emergency_relationship: "Mother",
    emergency_phone: "07037119544",
    job_title: "Brand Development strategist",
    department: "Strategy",
    date_joined: "11/24/2025",
    work_location: "15 Atiba Osborne street mende Maryland, Lagos, Nigeria,",
    supervisor: "Mrs Chidima",
    blood_group: "O+",
    bank_name: "Gtbank",
    account_number: "0612300236",
    hobbies: "Art",
    landmark: "Oguntade"
  },
  {
    name: "Ayomide Tunji-Bello",
    email: "ayomidetunjibello@gmail.com",
    dob: "1/19/2000",
    marital_status: "Single",
    address: "2 fatai close off Hon olufemi adebanjo street Egbeda akowonjo Lagos",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No 2 Fatai Close Off Hon Olufemi Adebanjo Street Egbeda Akowonjo Lagos",
    city_lga: "Alimosho",
    state_origin_residence: "Oyo /Lagos",
    work_email: "Oayomide@m.experiential-edge.com",
    phone: "08185306037",
    emergency_contact: "Tunji-Bello Oyeniyi",
    emergency_relationship: "Brother",
    emergency_phone: "08072610140",
    job_title: "Strategy and operations manager",
    department: "Strategy",
    date_joined: "11/10/2025",
    work_location: "Maryland",
    supervisor: "MD",
    blood_group: "A positive",
    bank_name: "Tunji-Bello Ayomide Oyelowo",
    account_number: "0361280104",
    hobbies: "Listen to music , traveling,",
    landmark: "Vulcanizer"
  },
  {
    name: "Idowu Jeremiah Olurakinyo",
    email: "idowuolurakinyo1@gmail.com",
    dob: "2/18/1981",
    marital_status: "Married",
    address: "6, Progressive Close Obabiyi Olambe Akute-Lagos",
    nationality: "Nigeria",
    staff_id: "012",
    home_address: "6, Progressive Close",
    city_lga: "Akute-Ifo",
    state_origin_residence: "Ondo State/Lagos",
    work_email: "iolurakinyo.m-edge.com",
    phone: "08033753322",
    emergency_contact: "Mrs Bola A. Olurakinyo",
    emergency_relationship: "Wife",
    emergency_phone: "07061981142",
    job_title: "Finance Manager",
    department: "Finance Department",
    date_joined: "1/10/2025",
    work_location: "Maryland Office",
    supervisor: "Mrs Vivian-MD",
    blood_group: "O",
    bank_name: "Zenith Bank",
    account_number: "4234743801",
    hobbies: "Football/Reading",
    landmark: "Lambe Junction"
  },
  {
    name: "QUEEN ADJOGRI",
    email: "queendavid2222@gmail.com",
    dob: "9/19/2002",
    marital_status: "Single",
    address: "Egbeda, Lagos",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Odo eran, Egbeda",
    city_lga: "Lagos/Alimosho LGA",
    state_origin_residence: "Delta State/ Lagos State",
    work_email: "queendavid2222@gmail.com",
    phone: "08021275017",
    emergency_contact: "Blessing Adjogri",
    emergency_relationship: "Sister",
    emergency_phone: "+234 808 036 3531",
    job_title: "Warehouse Operation- Stock control Intern",
    department: "E edge direct2u",
    date_joined: "1/21/2026",
    work_location: "9 Emmanuel Olorunfemi str Ogba, Lagos",
    supervisor: "Miss Lynda",
    blood_group: "0+",
    bank_name: "Zenith Bank",
    account_number: "2256266458",
    hobbies: "Reading Novels",
    landmark: "Pab Bus Stop"
  },
  {
    name: "Ndidiamaka Ekwueme",
    email: "ndidiie@gmail.com",
    dob: "7/8/1980",
    marital_status: "Married",
    address: "12 Ojelade Street, Fadeyi",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "12 Ojelade Street, Fadeyi",
    city_lga: "Mushin/ Lagos",
    state_origin_residence: "Anambra/",
    work_email: "nekueme@m.experiential-edge.com",
    phone: "09056871570",
    emergency_contact: "Gogo Sofiri Peterside",
    emergency_relationship: "Husband",
    emergency_phone: "07035412747",
    job_title: "Business/Account Manager",
    department: "Accounts/Strategy",
    date_joined: "10/7/2024",
    work_location: "Maryland",
    supervisor: "Chidimma Nwaeze",
    blood_group: "0+",
    bank_name: "GTB",
    account_number: "0010646501",
    hobbies: "Sight seeing",
    landmark: "Agip Bus"
  },
  {
    name: "Peter Obie",
    email: "obiepeter2@gmail.com",
    dob: "9/30/1984",
    marital_status: "Married",
    address: "321 road g close house 8 Festac town Lagos",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "321 road g close house 8 Festac town",
    city_lga: "Amuwo-Odofin",
    state_origin_residence: "Lagos",
    work_email: "opeter@m.experiential-edge.com",
    phone: "07010759243",
    emergency_contact: "Winifred obie",
    emergency_relationship: "Wife",
    emergency_phone: "0803 596 0847",
    job_title: "Creative Designer",
    department: "Design",
    date_joined: "11/7/2025",
    work_location: "Remote",
    supervisor: "Gloria",
    blood_group: "NA",
    bank_name: "GT bank",
    account_number: "0107058406",
    hobbies: null,
    landmark: null
  },
  {
    name: "BALA LISAG KOSY",
    email: "princesskbala31@gmail.com",
    dob: "7/22/2000",
    marital_status: "Single",
    address: "23 mopol barracks behind police workshop off mobolaji bank Anthony way ikeja",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "23 mopol barracks behind police workshop off mobolaji bank Anthony way ikeja",
    city_lga: "Ikeja",
    state_origin_residence: "Kaduna",
    work_email: "princesskbala31@gmail.com",
    phone: "08063371005",
    emergency_contact: "08034346517",
    emergency_relationship: "Mother",
    emergency_phone: "08122286586",
    job_title: "Assistant",
    department: "Warehouse Operations",
    date_joined: "2/3/2026",
    work_location: "No 9 Emmanuel Olorunfemi street. Ogba",
    supervisor: "Mr Theophilus Ayodeji",
    blood_group: "O+",
    bank_name: "First City Monument Bank(FCMB)",
    account_number: "4310688016",
    hobbies: "Movies",
    landmark: null
  },
  {
    name: "Ogiri Ann",
    email: "annogiri22@gmail.com",
    dob: "4/22/1987",
    marital_status: "Single",
    address: "War College Quarters Gwarimpa Abuja",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "War College Quarters Gwarimpa Abuja",
    city_lga: "Yala",
    state_origin_residence: "Cross River",
    work_email: "aogiri@m.experiential-edge.com",
    phone: "08022536606",
    emergency_contact: "08060873342",
    emergency_relationship: "Sister",
    emergency_phone: "08060873342",
    job_title: "Senior Procurement Manager",
    department: "Procurement",
    date_joined: "10/23/2024",
    work_location: "Abuja",
    supervisor: "Vivian Osigweh",
    blood_group: "O+",
    bank_name: "Access bank",
    account_number: "0025493926",
    hobbies: null,
    landmark: null
  },
  {
    name: "Daniel Zabe",
    email: "zabedaniel8@gmail.com",
    dob: "3/25/1995",
    marital_status: "Single",
    address: "Road 2 1A Diamond Estate Igando",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "Road 1A Diamond Estate Igando",
    city_lga: "Lagos Alimosho",
    state_origin_residence: "Bauchi state",
    work_email: "zabedaniel8@gmail.com",
    phone: "08129292596",
    emergency_contact: "0812 601 7260",
    emergency_relationship: "Brother",
    emergency_phone: "0812 601 7260",
    job_title: "Procurement",
    department: "Procurement",
    date_joined: "1/12/2026",
    work_location: "Atiba Osborne 15",
    supervisor: "Loveday",
    blood_group: "O+",
    bank_name: "Zabe Daniel",
    account_number: "2105297756",
    hobbies: null,
    landmark: null
  },
  {
    name: "Ewuoso Ayoola Joseph",
    email: "ewuoso53@gmail.com",
    dob: "9/17/1986",
    marital_status: "Married",
    address: "No 7 seye ogunsina close, new airport, alakia, ibadan",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "No 7 seye ogunsina close, nw airport",
    city_lga: "Ibadan",
    state_origin_residence: "Ogun/oyo",
    work_email: "ewuoso53@gmail.com",
    phone: "08064852972",
    emergency_contact: "Ogunsina funmike",
    emergency_relationship: "Wife",
    emergency_phone: "07069606688",
    job_title: "Regional sales manager",
    department: "Sales and marketing",
    date_joined: "11/24/2025",
    work_location: "Ibadan",
    supervisor: "Mrs vivian",
    blood_group: null,
    bank_name: "Access Bank",
    account_number: "0067979913",
    hobbies: null,
    landmark: "New airport"
  },
  {
    name: "Odesina Ayodeji Oluwaseye",
    email: "odesinaseye@gmail.com",
    dob: "8/23/1985",
    marital_status: "Married",
    address: "Ayandokun Compound behind Abiodun Atiba Grammar School Kosobo area, Oyo",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Ayandokun Compound behind Abiodun Atiba Grammar School Kosobo area, Oyo",
    city_lga: "Oyo/ Oyo East",
    state_origin_residence: "Oyo State",
    work_email: "odesinaseye@gmail.com",
    phone: "08033565543",
    emergency_contact: "08132527432",
    emergency_relationship: "Wife",
    emergency_phone: "08057833148",
    job_title: "VSR",
    department: "Regional Sales manager",
    date_joined: "11/25/2025",
    work_location: "Oyo town",
    supervisor: "Mr Ayoola",
    blood_group: "B+",
    bank_name: "GTB",
    account_number: "0845111036",
    hobbies: "Football",
    landmark: "Durbar Police station"
  },
  {
    name: "Adekunle Opeyemi",
    email: "goldsmile2000@gmail.com",
    dob: "8/13/2001",
    marital_status: "Single",
    address: "36 oduduwa street, Oworoshoki lagos",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Hse 9, Rd 1 lekki Atlantic garden, Ajah Lagos",
    city_lga: "Eti osa",
    state_origin_residence: "Oyo state",
    work_email: "goldsmile2000@gmail.com",
    phone: "09150954593",
    emergency_contact: "Yinka",
    emergency_relationship: "Sister",
    emergency_phone: "08133723804",
    job_title: "Admin and facility officer",
    department: "Human resources",
    date_joined: "2/2/2026",
    work_location: "Maryland",
    supervisor: "Mr Adedoyin",
    blood_group: "B+",
    bank_name: "UBA",
    account_number: "2386005862",
    hobbies: null,
    landmark: "Lekki garden phase 4"
  },
  {
    name: "Simon Hezekiah",
    email: "simonhezekiah67@gmail.com",
    dob: "8/24/1997",
    marital_status: "Single",
    address: "No 7, Adebayo street, peace avenue, araromi bus stop. Adiyan, Ogun state",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No 9, Adebayo street,peace avenue, araromi bus stop, Adiyan ,Ogun state",
    city_lga: "Adiyan",
    state_origin_residence: "Akwaibom state/ Ogun state",
    work_email: "simonhezekiah67@gmail.com",
    phone: "09077803201",
    emergency_contact: "+234 902 007 9467",
    emergency_relationship: "Mother",
    emergency_phone: "0913 755 8229",
    job_title: "Logistics Executive",
    department: "Modern Trade",
    date_joined: "10/6/2025",
    work_location: "Maryland",
    supervisor: "Mrs Chidinma Mordi",
    blood_group: "O+",
    bank_name: "Access Bank",
    account_number: "1834001540",
    hobbies: "Cooking",
    landmark: "Agbado Oja"
  },
  {
    name: "ORJI MICHAEL UCHECHI",
    email: "MICHAEORJI222@GMAIL.COM",
    dob: "5/20/2002",
    marital_status: "Single",
    address: "23, BAJULAYE SREET, SHOMOLU",
    nationality: "NIGERIAN",
    staff_id: null,
    home_address: "23, BAJULAYIE STREET",
    city_lga: "SHOMOLU/LAGOS",
    state_origin_residence: "ABIA/BENDE",
    work_email: "MICHAEORJI222@GMAIL.COM",
    phone: "09017542793",
    emergency_contact: "ORJI MICHAEL UCHECHI",
    emergency_relationship: "BROTHER",
    emergency_phone: "08038908818",
    job_title: "SOCIAL MEDIA/ GRAPHICS DESIGNER",
    department: "CREATIVE",
    date_joined: "2/12/2026",
    work_location: "MARYLAND",
    supervisor: "Head Of Creative",
    blood_group: "0-",
    bank_name: "Guaranty Trust Bank (GTB)",
    account_number: "0595274519",
    hobbies: "reading",
    landmark: "ONIPANU"
  },
  {
    name: "Jonah Daniel Agada",
    email: "dannyjagas03@gmail.Com",
    dob: "4/3/1982",
    marital_status: "Married",
    address: "25 Fasali street Abar",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "25 fasali street Abaranji ikotun lagos",
    city_lga: "Alimosho",
    state_origin_residence: "Kogi state",
    work_email: "dannyjagas03@gmail.Com",
    phone: "07019147585",
    emergency_contact: "0705 407 0771",
    emergency_relationship: "Brother",
    emergency_phone: "0705 407 0771",
    job_title: "SUPERNUMERARY POLICE",
    department: "Driving",
    date_joined: "1/21/2026",
    work_location: "Maryland",
    supervisor: "MR LOVEDAY",
    blood_group: "AA",
    bank_name: "Zenith Bank",
    account_number: "2282251026",
    hobbies: "Driving",
    landmark: "Agbaduma Allom opposite UEC church"
  },
  {
    name: "Chiamaka Favour",
    email: "chiamakacf4286046@gmail.com",
    dob: "1/4/1989",
    marital_status: "Married",
    address: "Igando",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "Igando",
    city_lga: "Alimosho",
    state_origin_residence: "Abia state",
    work_email: "chiamakacf4286046@gmail.com",
    phone: "08037486841",
    emergency_contact: "Chukwu",
    emergency_relationship: "Brother",
    emergency_phone: "+234 806 848 6193",
    job_title: "Househelp",
    department: "Househelp",
    date_joined: "12/2/2024",
    work_location: "Igando",
    supervisor: "MD",
    blood_group: "No idea",
    bank_name: "Uba",
    account_number: "2356669429",
    hobbies: "Music",
    landmark: "Igando"
  },
  {
    name: "David Oyedepo",
    email: "tosinoyedepo5@gmail.com",
    dob: "7/13/1977",
    marital_status: "Married",
    address: "12,Soore Close Orile Agege Lagos off jibowu street",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "12, Soore Close Orile Agege off Old Ota Road",
    city_lga: "Orile Agege",
    state_origin_residence: "Kwara/Lagos",
    work_email: "davidoyedepo@eedge",
    phone: "09077689952",
    emergency_contact: "08125546996",
    emergency_relationship: "Wife",
    emergency_phone: "08125546996",
    job_title: "VSR",
    department: "E-Edge Direct 2 you",
    date_joined: "11/12/2021",
    work_location: "Surulere",
    supervisor: "Valentine",
    blood_group: "O+",
    bank_name: "Opay",
    account_number: "08178044846",
    hobbies: "Basketball",
    landmark: "Ilepo Bus stop"
  },
  {
    name: "Prince Donald",
    email: "princedonald34@gmail.com",
    dob: "10/23/2003",
    marital_status: "Single",
    address: "No 31 onajimi street off Pedro road bariga",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "No 31 onajimi street off Pedro road bariga",
    city_lga: "Bariga",
    state_origin_residence: "Abia state / Lagos",
    work_email: "princedonald34@gmail.com",
    phone: "08104590850",
    emergency_contact: "Chief Emeka peters",
    emergency_relationship: "Cousin",
    emergency_phone: "+234 803 070 4448",
    job_title: "HR / operations and capability executive",
    department: "Human Resource",
    date_joined: "3/16/2026",
    work_location: "15 Atiba Osborne street",
    supervisor: "Loveday lucky",
    blood_group: "O+",
    bank_name: "First bank plc",
    account_number: "3186057707",
    hobbies: null,
    landmark: "Onajimi street"
  },
  {
    name: "Chidinma Mordi (Obidiegwu)",
    email: "chidima.obidiegwu@gmail.com",
    dob: "11/26/1986",
    marital_status: "Married",
    address: "No. 31B surulere street, Alagbole",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No. 31B surulere street, Alagbole",
    city_lga: "Ogun state",
    state_origin_residence: "Anambra /Ogun state",
    work_email: "ochidinma@edgedirect2u.com.ng",
    phone: "08037674270",
    emergency_contact: "Mr Nkem Mordi",
    emergency_relationship: "Husband",
    emergency_phone: "08064829379",
    job_title: "Customer services & Warehouse Manager",
    department: "Supply Chain/ Distribution",
    date_joined: "10/14/2024",
    work_location: "Maryland",
    supervisor: "Mrs Vivian Osigweh (MD)",
    blood_group: "AB+",
    bank_name: "Keystone bank",
    account_number: "6020627995",
    hobbies: null,
    landmark: null
  },
  {
    name: "Uke-Ulim Ekunke-Ogah",
    email: "ogahuke@gmail.com",
    dob: "9/7/1992",
    marital_status: "Married",
    address: "296 Murtala Muhammed Way, Yaba. Lagos",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "296 Murtala Muhammed Way, Yaba, Lagos Mainland.",
    city_lga: "Lagos",
    state_origin_residence: null,
    work_email: "uogah@m.experiential-edge.com",
    phone: "08037169208",
    emergency_contact: "Toritsefe Aigbedion",
    emergency_relationship: "Family friend",
    emergency_phone: "0902 231 8723",
    job_title: "Senior Strategy and Account Manager",
    department: "Strategy/Accounts",
    date_joined: "4/1/2026",
    work_location: "Mende/Maryland",
    supervisor: "ED - Mrs Vivian Osigwe",
    blood_group: "O+",
    bank_name: "Zenith Bank PLC",
    account_number: "1005096128",
    hobbies: null,
    landmark: "Alagomeji/ Mobolaji Johnson Railway Station"
  },
  {
    name: "Ajayi Adedayo",
    email: "dedasco11@gmail.com",
    dob: "2/8/1995",
    marital_status: "Single",
    address: "17 Oyemomilara, Off command road, Ile iwe bus stop.",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "17, Oyemomilara street, Meiran Lagos",
    city_lga: "Meiran",
    state_origin_residence: "Ekiti",
    work_email: "Aajayi@m.experiential-edge.com",
    phone: "08140079684",
    emergency_contact: "08163182050",
    emergency_relationship: "Single",
    emergency_phone: "08140079784",
    job_title: "HR Manager",
    department: "Human Resource",
    date_joined: "3/30/2026",
    work_location: "Ikeja, Maryland",
    supervisor: "MD",
    blood_group: "OO+",
    bank_name: "Opay",
    account_number: "8140079684",
    hobbies: null,
    landmark: "Ile iwe bus stop, Command"
  },
  {
    name: "Ademola Famade",
    email: "adetopemi@gmail.com",
    dob: "4/16/1971",
    marital_status: "Married",
    address: "3, Platinum Street, God's Own Estate, Elepete, Ikorodu",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "3, Platinum Street, God's Own Estate, Elepete, Ikorodu",
    city_lga: "Ikorodu",
    state_origin_residence: "Lagos",
    work_email: "adetopemi@gmail.com",
    phone: "08028487667",
    emergency_contact: "Ademola Famade",
    emergency_relationship: "Self",
    emergency_phone: "08028487667",
    job_title: "Head of Finance",
    department: "Finance",
    date_joined: "4/7/2026",
    work_location: "Maryland",
    supervisor: "Managing Director",
    blood_group: "AA",
    bank_name: "Wema Bank",
    account_number: "0121553763",
    hobbies: "Farming",
    landmark: "Transformer Bustop"
  },
  {
    name: "Lawal Olufemi Jamiu",
    email: "lawalolufemijamiu@gmail.com",
    dob: "5/5/1989",
    marital_status: "Married",
    address: "No 5, Itun Dega Quarters, Erinlu Ijebu Ode, Ogun State",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "No 5, Itun Dega Quarters, Erinlu Ijebu Ode, Ogun State",
    city_lga: "Ijebu/ Ijebu Ode",
    state_origin_residence: "Ogun / Ogun",
    work_email: "Lolufemi@m.experiential-edge.com",
    phone: "08130155784",
    emergency_contact: "07055543374",
    emergency_relationship: "Brother",
    emergency_phone: "07055543374",
    job_title: "Logistics/Fleet Manager",
    department: "Human Resource",
    date_joined: "4/13/2026",
    work_location: "Maryland",
    supervisor: "MD",
    blood_group: "A+",
    bank_name: "UBA",
    account_number: "2296314449",
    hobbies: "Travelling",
    landmark: null
  },
  {
    name: "Chiedozie Joseph Orji",
    email: "chiedozieorji7@gmail.com",
    dob: "3/14/1982",
    marital_status: "Married",
    address: "20, Diffri road abaranje ikotun",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "20, Diffri road abaranje ikotun",
    city_lga: "Ikotun alimosho",
    state_origin_residence: "Enugu State",
    work_email: "Corji@m.experiential- edge.com",
    phone: "08068349700",
    emergency_contact: "Benita chiedozie",
    emergency_relationship: "Spouse",
    emergency_phone: "081375333020",
    job_title: "Project executive",
    department: "Operations",
    date_joined: "5/4/2026",
    work_location: "Maryland",
    supervisor: "Chiedozie Joseph Orji",
    blood_group: "O",
    bank_name: "GTB",
    account_number: "0041943284",
    hobbies: "Traveling, farming and electrical hardware",
    landmark: null
  },
  {
    name: "Amadi Amobi Elias",
    email: "amad17amobi@gmail.com",
    dob: "2/9/1980",
    marital_status: "Married",
    address: "Road 2 house 1 Diamond estate isheri olofin Alimosho Lagos",
    nationality: "Nigeria",
    staff_id: null,
    home_address: "Road 2 house 1 Diamond estate isheri olofin Alimosho",
    city_lga: "Alimosho",
    state_origin_residence: "Lagos",
    work_email: "aelias@m.experiential-edge.com",
    phone: "08021190284",
    emergency_contact: "Amadi Anita odinakachukwu",
    emergency_relationship: "Sister",
    emergency_phone: "08121194621",
    job_title: "Senior project & Operations Manager",
    department: "Operations",
    date_joined: "5/4/2026",
    work_location: "Lagos",
    supervisor: "MD",
    blood_group: "O+",
    bank_name: "Amadi Amobi Elias",
    account_number: "6000056636",
    hobbies: "Football, reading, travelling and music",
    landmark: "Diamond"
  },
  {
    name: "Abdulfatai Abdulsalami",
    email: "aabdulsslami424@gmail.com",
    dob: "2/13/1975",
    marital_status: "Married",
    address: "17 oyinbo orunmila street unity estate ojodu",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "17 oyinbo orunmila unity estate ojodu",
    city_lga: "ikeja",
    state_origin_residence: "kogi",
    work_email: "abdulsalami424@gmail.com",
    phone: "07086546219",
    emergency_contact: "Faisal lawal",
    emergency_relationship: "friends",
    emergency_phone: "08143240257",
    job_title: "ASM",
    department: "Sales4",
    date_joined: "5/4/2026",
    work_location: "lagos",
    supervisor: "MD",
    blood_group: "AA",
    bank_name: "zenith bank",
    account_number: "2001743672",
    hobbies: "Reading and jogging",
    landmark: "Grammar school ojodu"
  },
  {
    name: "Okoye Favour Chidinma",
    email: "okoyefavour16@gmail.com",
    dob: "12/22/2003",
    marital_status: "Single",
    address: "No 6 dapson road , okeira ogba Lagos state",
    nationality: "Nigerian",
    staff_id: null,
    home_address: "No 6 dapson road okeira ogba Lagos state",
    city_lga: "Ogba/ifako Ijaiye local government",
    state_origin_residence: "Anambra/ Lagos",
    work_email: null,
    phone: "09012133017",
    emergency_contact: "08075584571",
    emergency_relationship: "Single",
    emergency_phone: "09012133017",
    job_title: "Account manager",
    department: "Operation and Account department",
    date_joined: "5/11/2026",
    work_location: "15 Atiba Mende Maryland",
    supervisor: "Madam Chidinma",
    blood_group: "O+",
    bank_name: "United bank of Africa",
    account_number: "2366011740",
    hobbies: "Watching movies",
    landmark: "Ogba bus stop"
  }
];

function deriveRoleCode(jobTitle = '', department = '') {
  const jt = String(jobTitle).toLowerCase();
  const dept = String(department).toLowerCase();

  if (jt.includes('cto') || jt.includes('chief technology')) return 'CTO';
  if (jt.includes('ceo') || jt.includes('chief executive') || jt.includes('managing director')) return 'CEO';
  if (dept.includes('hr') || dept.includes('human resource') || jt.includes('hr manager')) return 'HR_MANAGER';
  if (dept.includes('finance') || jt.includes('finance manager') || jt.includes('head of finance') || jt.includes('accountant')) return 'ACCOUNTANT';
  if (dept.includes('sales') || jt.includes('sales') || jt.includes('vsr')) return 'SALES_AGENT';
  if (dept.includes('operation') || dept.includes('compliance') || jt.includes('compliance') || jt.includes('field')) return 'FIELD_AGENT';
  if (jt.includes('supervisor')) return 'SUPERVISOR';
  if (jt.includes('manager')) return 'MANAGER';
  return 'STAFF_MEMBER';
}

function deriveRankCode(jobTitle = '', department = '') {
  const jt = String(jobTitle).toLowerCase();
  const dept = String(department).toLowerCase();

  if (jt.includes('cto')) return 'CTO';
  if (jt.includes('ceo') || jt.includes('managing director')) return 'CEO';
  if (dept.includes('hr') || jt.includes('hr manager')) return 'HR';
  if (dept.includes('finance') || jt.includes('finance manager') || jt.includes('head of finance')) return 'ACCOUNTANT';
  if (jt.includes('senior') || jt.includes('head of') || jt.includes('manager')) return 'MANAGER';
  if (jt.includes('supervisor')) return 'SUPERVISOR';
  return 'STAFF';
}

function splitFullName(fullName = '') {
  const parts = String(fullName).trim().split(/\s+/);
  if (parts.length === 1) {
    return { first_name: parts[0], last_name: parts[0] };
  }
  const first_name = parts[0];
  const last_name = parts.slice(1).join(' ');
  return { first_name, last_name };
}

export const staffImportService = {
  /**
   * Idempotently imports all authoritative staff records.
   */
  async importAuthoritativeStaff(dataset = AUTHORITATIVE_STAFF_DATASET) {
    const results = {
      total_records: dataset.length,
      processed: 0,
      employees_created: 0,
      employees_updated: 0,
      accounts_created: 0,
      accounts_updated: 0,
      duplicates_detected: 0,
      flagged_for_review: 0,
      review_items: [],
      errors: []
    };

    const existingUsers = await db.find('users');
    const existingEmployees = await db.find('employees');
    const existingDepartments = await db.find('departments');

    const defaultPasswordHash = bcrypt.hashSync('ChangeMe123!', 10);

    for (let i = 0; i < dataset.length; i++) {
      const record = dataset[i];
      try {
        results.processed++;

        // 1. Normalize identifiers
        const normalizedEmail = normalizeEmail(record.email);
        const normalizedWorkEmail = record.work_email && !record.work_email.toLowerCase().includes('not been assigned') && !record.work_email.toLowerCase().includes('nil')
          ? normalizeEmail(record.work_email.replace(/\s+/g, ''))
          : null;
        const normalizedPhone = normalizePhone(record.phone);
        const staffId = record.staff_id ? String(record.staff_id).trim() : null;

        // Determine primary login email/identifier
        const primaryLoginEmail = normalizedWorkEmail || normalizedEmail || (normalizedPhone ? `${normalizedPhone.replace('+', '')}@edgewforce.internal` : null);

        // 2. Check for missing/ambiguous fields needing review
        const reviewReasons = [];
        if (!staffId) reviewReasons.push('Missing official Staff ID (flagged for HR generation)');
        if (!normalizedWorkEmail) reviewReasons.push('Work email not yet assigned');
        if (record.blood_group === 'No idea' || record.blood_group === 'NA' || !record.blood_group) reviewReasons.push('Blood group unconfirmed');
        if (record.supervisor && record.supervisor.length > 30) reviewReasons.push('Multiple/complex reporting lines in supervisor field');

        const isFlagged = reviewReasons.length > 0;
        if (isFlagged) {
          results.flagged_for_review++;
          results.review_items.push({
            name: record.name,
            staff_id: staffId || 'UNASSIGNED',
            reasons: reviewReasons
          });
        }

        // 3. Match existing user / employee (Matching priority)
        let matchedUser = null;
        let matchedEmployee = null;

        if (staffId) {
          matchedEmployee = existingEmployees.find(e => e.staff_id === staffId || e.employee_code === staffId || e.employee_code === `EMP-${staffId}`);
        }
        if (!matchedEmployee && normalizedWorkEmail) {
          matchedEmployee = existingEmployees.find(e => e.work_email === normalizedWorkEmail || e.personal_email === normalizedWorkEmail);
        }
        if (!matchedEmployee && normalizedEmail) {
          matchedEmployee = existingEmployees.find(e => e.personal_email === normalizedEmail || e.work_email === normalizedEmail);
        }
        if (!matchedEmployee && normalizedPhone) {
          matchedEmployee = existingEmployees.find(e => normalizePhone(e.phone) === normalizedPhone);
        }
        if (!matchedEmployee && record.name) {
          matchedEmployee = existingEmployees.find(e => 
            (e.full_name && e.full_name.toLowerCase() === record.name.toLowerCase()) || 
            (`${e.first_name || ''} ${e.last_name || ''}`.trim().toLowerCase() === record.name.toLowerCase())
          );
        }

        if (matchedEmployee?.user_id) {
          matchedUser = existingUsers.find(u => Number(u.id) === Number(matchedEmployee.user_id));
        }

        if (!matchedUser) {
          if (normalizedWorkEmail) matchedUser = existingUsers.find(u => u.email === normalizedWorkEmail);
          if (!matchedUser && normalizedEmail) matchedUser = existingUsers.find(u => u.email === normalizedEmail);
          if (!matchedUser && normalizedPhone) matchedUser = existingUsers.find(u => normalizePhone(u.phone) === normalizedPhone);
          if (!matchedUser && record.name) matchedUser = existingUsers.find(u => u.full_name && u.full_name.toLowerCase() === record.name.toLowerCase());
        }

        const roleCode = deriveRoleCode(record.job_title, record.department);
        const rankCode = deriveRankCode(record.job_title, record.department);
        const { first_name, last_name } = splitFullName(record.name);

        // Find department ID if exists
        const matchedDept = existingDepartments.find(d => 
          d.name.toLowerCase() === (record.department || '').toLowerCase() ||
          d.code.toLowerCase() === (record.department || '').toLowerCase()
        );

        // 4. Create or Update User Account
        let userId = null;
        if (matchedUser) {
          userId = matchedUser.id;
          results.duplicates_detected++;
          await db.update('users', matchedUser.id, {
            full_name: record.name,
            phone: normalizedPhone || matchedUser.phone,
            raw_phone: record.phone,
            onboarding_status: matchedUser.onboarding_status || 'Active'
          });
          results.accounts_updated++;
        } else {
          const newUser = await db.insert('users', {
            company_id: 1,
            full_name: record.name,
            email: primaryLoginEmail,
            phone: normalizedPhone,
            raw_phone: record.phone,
            password_hash: defaultPasswordHash,
            role_code: roleCode,
            status: 'active',
            requires_password_change: true,
            onboarding_status: 'Account Created',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          });
          userId = newUser.id;
          existingUsers.push(newUser);
          results.accounts_created++;
        }

        // 5. Create or Update Employee Record
        const employeePayload = {
          company_id: 1,
          user_id: userId,
          employee_code: staffId ? `EMP-${staffId}` : `EMP-${1000 + i + 10}`,
          staff_id: staffId,
          first_name,
          last_name,
          full_name: record.name,
          personal_email: normalizedEmail,
          work_email: normalizedWorkEmail,
          phone: normalizedPhone,
          date_of_birth: record.dob,
          marital_status: record.marital_status,
          nationality: record.nationality || 'Nigerian',
          address: record.address,
          home_address: record.home_address,
          city_lga: record.city_lga,
          state_of_origin: record.state_origin_residence,
          state_of_residence: record.state_origin_residence,
          landmark: record.landmark,
          department_id: matchedDept ? matchedDept.id : null,
          department: record.department,
          department_raw: record.department,
          position: record.job_title,
          date_of_joining: record.date_joined,
          hire_date: record.date_joined ? new Date(record.date_joined).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10),
          work_location: record.work_location,
          supervisor_name: record.supervisor,
          emergency_contact_name: record.emergency_contact,
          emergency_contact_relationship: record.emergency_relationship,
          emergency_contact_phone: record.emergency_phone,
          blood_group: record.blood_group,
          bank_name: record.bank_name,
          account_number: record.account_number,
          hobbies_interests: record.hobbies,
          rank_code: rankCode,
          flagged_for_review: isFlagged,
          review_reason: reviewReasons.join('; '),
          onboarding_status: 'Account Created',
          status: 'active',
          updated_at: new Date().toISOString()
        };

        if (matchedEmployee) {
          await db.update('employees', matchedEmployee.id, employeePayload);
          results.employees_updated++;
        } else {
          employeePayload.created_at = new Date().toISOString();
          const newEmp = await db.insert('employees', employeePayload);
          existingEmployees.push(newEmp);
          results.employees_created++;
        }
      } catch (err) {
        logger.error(`Error importing record for ${record.name}: ${err.message}`);
        results.errors.push({ name: record.name, error: err.message });
      }
    }

    logger.info(`Authoritative staff import complete: ${results.employees_created} employees created, ${results.accounts_created} accounts created.`);
    return results;
  }
};
