-- ==============================================================================
-- EDGEWFORCE - MIGRATION 004: WORK LOCATIONS & EMPLOYEE LOCATION ASSIGNMENTS
-- Dynamic Multi-Location Management, Geofencing, Temporary Assignments & Audit Trail
-- ==============================================================================

-- 1. WORK LOCATIONS TABLE
CREATE TABLE IF NOT EXISTS public.work_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    name TEXT NOT NULL,
    location_type TEXT NOT NULL DEFAULT 'Office'
        CHECK (location_type IN (
            'Office',
            'Market',
            'Store',
            'Supermarket',
            'Client Location',
            'Warehouse',
            'Branch',
            'Distributor',
            'Event Location',
            'Other'
        )),
    address TEXT,
    state TEXT NOT NULL DEFAULT 'Lagos',
    lga TEXT,
    city TEXT,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    geofence_radius_meters INTEGER NOT NULL DEFAULT 150
        CHECK (geofence_radius_meters >= 20 AND geofence_radius_meters <= 10000),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),
    created_by UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT work_locations_company_name_unique UNIQUE(company_id, name)
);

-- 2. EMPLOYEE LOCATION ASSIGNMENTS TABLE
CREATE TABLE IF NOT EXISTS public.employee_location_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    employee_id UUID NOT NULL
        REFERENCES public.employees(id)
        ON DELETE CASCADE,
    location_id BIGINT NOT NULL
        REFERENCES public.work_locations(id)
        ON DELETE CASCADE,
    assignment_type TEXT NOT NULL DEFAULT 'primary'
        CHECK (assignment_type IN ('primary', 'secondary', 'temporary', 'permanent')),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    assigned_by UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. LOCATION ASSIGNMENT AUDIT HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.location_assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    employee_id UUID NOT NULL
        REFERENCES public.employees(id)
        ON DELETE CASCADE,
    previous_location_id BIGINT
        REFERENCES public.work_locations(id)
        ON DELETE SET NULL,
    previous_location_name TEXT,
    new_location_id BIGINT
        REFERENCES public.work_locations(id)
        ON DELETE SET NULL,
    new_location_name TEXT,
    assignment_type TEXT NOT NULL DEFAULT 'primary',
    action TEXT NOT NULL DEFAULT 'ASSIGNED',
    changed_by UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,
    changed_by_name TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. INDEXES
CREATE INDEX IF NOT EXISTS idx_work_locations_company ON public.work_locations(company_id);
CREATE INDEX IF NOT EXISTS idx_work_locations_state ON public.work_locations(state);
CREATE INDEX IF NOT EXISTS idx_work_locations_type ON public.work_locations(location_type);
CREATE INDEX IF NOT EXISTS idx_emp_loc_assign_employee ON public.employee_location_assignments(employee_id);
CREATE INDEX IF NOT EXISTS idx_emp_loc_assign_location ON public.employee_location_assignments(location_id);
CREATE INDEX IF NOT EXISTS idx_emp_loc_assign_active ON public.employee_location_assignments(employee_id, is_active);
CREATE INDEX IF NOT EXISTS idx_loc_history_employee ON public.location_assignment_history(employee_id);

-- 5. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.work_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_location_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_assignment_history ENABLE ROW LEVEL SECURITY;

-- Work Locations Policy
CREATE POLICY work_locations_tenant_isolation ON public.work_locations
    FOR ALL
    USING (company_id = (
        SELECT company_id FROM public.profiles WHERE id = auth.uid()
    ))
    WITH CHECK (company_id = (
        SELECT company_id FROM public.profiles WHERE id = auth.uid()
    ));

-- Employee Location Assignments Policy
CREATE POLICY employee_location_assignments_tenant_isolation ON public.employee_location_assignments
    FOR ALL
    USING (company_id = (
        SELECT company_id FROM public.profiles WHERE id = auth.uid()
    ))
    WITH CHECK (company_id = (
        SELECT company_id FROM public.profiles WHERE id = auth.uid()
    ));

-- Location Assignment History Policy
CREATE POLICY location_assignment_history_tenant_isolation ON public.location_assignment_history
    FOR ALL
    USING (company_id = (
        SELECT company_id FROM public.profiles WHERE id = auth.uid()
    ))
    WITH CHECK (company_id = (
        SELECT company_id FROM public.profiles WHERE id = auth.uid()
    ));
